import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';

export const useStatusCardStyles = makeStyles((theme: Theme) => ({
  card: {
    position: 'relative',
    borderRadius: 12,
    background: `linear-gradient(135deg, ${theme?.palette?.background?.paper || '#1e293b'}95 0%, ${theme?.palette?.background?.default || '#0f172a'}75 100%)`,
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.08)'}`,
    boxShadow: `0 2px 8px ${theme?.palette?.mode === 'dark' ? 'rgba(0, 0, 0, 0.2)' : 'rgba(0, 0, 0, 0.06)'}`,
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    backdropFilter: 'blur(8px)',
    '&:hover': {
      transform: 'translateY(-2px)',
      boxShadow: `0 6px 16px ${theme?.palette?.mode === 'dark' ? 'rgba(0, 0, 0, 0.3)' : 'rgba(0, 0, 0, 0.1)'}`,
      borderColor: `${theme?.palette?.primary?.main || '#4ade80'}20`,
    },
  },
  cardHealthy: {
    borderColor: `${theme?.palette?.success?.main || '#10b981'}30`,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      background: `linear-gradient(180deg, ${theme?.palette?.success?.main || '#10b981'}, ${theme?.palette?.success?.dark || '#059669'})`,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardWarning: {
    borderColor: `${theme?.palette?.warning?.main || '#f59e0b'}30`,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      background: `linear-gradient(180deg, ${theme?.palette?.warning?.main || '#f59e0b'}, ${theme?.palette?.warning?.dark || '#d97706'})`,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardCritical: {
    borderColor: `${theme?.palette?.error?.main || '#ef4444'}30`,
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      background: `linear-gradient(180deg, ${theme?.palette?.error?.main || '#ef4444'}, ${theme?.palette?.error?.dark || '#dc2626'})`,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardContent: {
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    position: 'relative',
    zIndex: 1,
    '@media (max-width: 768px)': {
      padding: '10px 12px',
      gap: 8,
    },
  },
  iconContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 8,
    background: `linear-gradient(135deg, ${theme?.palette?.action?.disabledBackground || 'rgba(148, 163, 184, 0.08)'} 0%, transparent 100%)`,
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.08)'}`,
    flexShrink: 0,
    alignSelf: 'flex-start',
    transition: 'all 0.25s ease',
    '& svg, & .MuiIcon-root': {
      fontSize: 18,
    },
    '@media (max-width: 768px)': {
      width: 32,
      height: 32,
      borderRadius: 7,
      '& svg, & .MuiIcon-root': {
        fontSize: 16,
      },
    },
  },
  iconDefault: {
    color: theme?.palette?.primary?.main || '#4ade80',
    borderColor: `${theme?.palette?.primary?.main || '#4ade80'}20`,
    background: `linear-gradient(135deg, ${theme?.palette?.primary?.main || '#4ade80'}12, transparent)`,
  },
  iconHealthy: {
    color: theme?.palette?.success?.main || '#10b981',
    borderColor: `${theme?.palette?.success?.main || '#10b981'}20`,
    background: `linear-gradient(135deg, ${theme?.palette?.success?.main || '#10b981'}12, transparent)`,
  },
  iconWarning: {
    color: theme?.palette?.warning?.main || '#f59e0b',
    borderColor: `${theme?.palette?.warning?.main || '#f59e0b'}20`,
    background: `linear-gradient(135deg, ${theme?.palette?.warning?.main || '#f59e0b'}12, transparent)`,
  },
  iconCritical: {
    color: theme?.palette?.error?.main || '#ef4444',
    borderColor: `${theme?.palette?.error?.main || '#ef4444'}20`,
    background: `linear-gradient(135deg, ${theme?.palette?.error?.main || '#ef4444'}12, transparent)`,
  },
  content: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  title: {
    fontSize: '0.7rem',
    fontWeight: 600,
    color: theme?.palette?.text?.secondary || '#94a3b8',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    lineHeight: 1.2,
    opacity: 0.9,
  },
  valueRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
  },
  value: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: theme?.palette?.text?.primary || '#f1f5f9',
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    '@media (max-width: 768px)': {
      fontSize: '1.3rem',
    },
  },
  trend: {
    fontSize: '0.65rem',
    fontWeight: 600,
    fontFamily: 'monospace',
    padding: '3px 6px',
    borderRadius: 5,
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.1)'}`,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    whiteSpace: 'nowrap',
  },
  trendUp: {
    color: theme?.palette?.success?.main || '#10b981',
    background: `${theme?.palette?.success?.main || '#10b981'}12`,
    borderColor: `${theme?.palette?.success?.main || '#10b981'}25`,
  },
  trendDown: {
    color: theme?.palette?.error?.main || '#ef4444',
    background: `${theme?.palette?.error?.main || '#ef4444'}12`,
    borderColor: `${theme?.palette?.error?.main || '#ef4444'}25`,
  },
  trendNeutral: {
    color: theme?.palette?.text?.disabled || '#64748b',
    background: `${theme?.palette?.text?.disabled || '#64748b'}10`,
    borderColor: `${theme?.palette?.text?.disabled || '#64748b'}20`,
  },
  trendSymbol: {
    fontSize: '0.75rem',
    fontWeight: 700,
  },
}));
