import { makeStyles } from '@mui/styles';
import { Theme, alpha } from '@mui/material/styles';

export const useStatusCardStyles = makeStyles((theme: Theme) => ({
  card: {
    position: 'relative',
    borderRadius: 14,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.12)}`,
    boxShadow: `0 4px 16px ${alpha(theme.palette.common.black, 0.1)}`,
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
    '&:hover': {
      transform: 'translateY(-2px)',
      backgroundColor: alpha(theme.palette.common.white, 0.1),
      boxShadow: `0 8px 24px ${alpha(theme.palette.common.black, 0.15)}`,
    },
  },
  cardHealthy: {
    borderColor: alpha(theme.palette.success.main, 0.3),
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      backgroundColor: theme.palette.success.main,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardWarning: {
    borderColor: alpha(theme.palette.warning.main, 0.3),
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      backgroundColor: theme.palette.warning.main,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardCritical: {
    borderColor: alpha(theme.palette.error.main, 0.3),
    '&::before': {
      content: '""',
      position: 'absolute',
      top: 0,
      left: 0,
      width: 3,
      height: '100%',
      backgroundColor: theme.palette.error.main,
      borderRadius: '3px 0 0 3px',
    },
  },
  cardContent: {
    padding: '14px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    position: 'relative',
    zIndex: 1,
    '@media (max-width: 768px)': {
      padding: '12px 14px',
      gap: 8,
    },
  },
  iconContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    border: `1px solid ${alpha(theme.palette.common.white, 0.1)}`,
    flexShrink: 0,
    alignSelf: 'flex-start',
    transition: 'all 0.25s ease',
    '& svg, & .MuiIcon-root': {
      fontSize: 18,
    },
    '@media (max-width: 768px)': {
      width: 32,
      height: 32,
      borderRadius: 8,
      '& svg, & .MuiIcon-root': {
        fontSize: 16,
      },
    },
  },
  iconDefault: {
    color: theme.palette.primary.main,
    borderColor: alpha(theme.palette.primary.main, 0.3),
    backgroundColor: alpha(theme.palette.primary.main, 0.15),
  },
  iconHealthy: {
    color: theme.palette.success.main,
    borderColor: alpha(theme.palette.success.main, 0.3),
    backgroundColor: alpha(theme.palette.success.main, 0.15),
  },
  iconWarning: {
    color: theme.palette.warning.main,
    borderColor: alpha(theme.palette.warning.main, 0.3),
    backgroundColor: alpha(theme.palette.warning.main, 0.15),
  },
  iconCritical: {
    color: theme.palette.error.main,
    borderColor: alpha(theme.palette.error.main, 0.3),
    backgroundColor: alpha(theme.palette.error.main, 0.15),
  },
  content: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  title: {
    fontSize: '0.7rem',
    fontWeight: 600,
    color: theme.palette.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    lineHeight: 1.2,
  },
  valueRow: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 8,
    flexWrap: 'wrap',
  },
  value: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    '@media (max-width: 768px)': {
      fontSize: '1.3rem',
    },
  },
  trend: {
    fontSize: '0.65rem',
    fontWeight: 600,
    padding: '4px 8px',
    borderRadius: 999,
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
    whiteSpace: 'nowrap',
  },
  trendUp: {
    color: theme.palette.success.main,
    backgroundColor: alpha(theme.palette.success.main, 0.15),
    border: `1px solid ${alpha(theme.palette.success.main, 0.3)}`,
  },
  trendDown: {
    color: theme.palette.error.main,
    backgroundColor: alpha(theme.palette.error.main, 0.15),
    border: `1px solid ${alpha(theme.palette.error.main, 0.3)}`,
  },
  trendNeutral: {
    color: theme.palette.text.disabled,
    backgroundColor: alpha(theme.palette.text.disabled, 0.1),
    border: `1px solid ${alpha(theme.palette.text.disabled, 0.2)}`,
  },
  trendSymbol: {
    fontSize: '0.75rem',
    fontWeight: 700,
  },
}));
