import { makeStyles } from '@mui/styles';
import { Theme, alpha } from '@mui/material/styles';

export const useAppStyles = makeStyles((theme: Theme) => ({
  appContainer: {
    display: 'flex',
    height: '100vh',
    width: '100vw',
    backgroundColor: theme.palette.background.default,
    position: 'relative' as const,
    overflow: 'hidden',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
    marginLeft: 0,
    transition: 'margin-left 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  canvas: {
    flex: 1,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    visibility: 'visible',
  },
  sidebarContainer: {
    position: 'fixed' as const,
    left: 16,
    top: 16,
    bottom: 16,
    width: 280,
    zIndex: 1000,
    transition: 'width 0.4s cubic-bezier(0.4, 0, 0.2, 1), transform 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'width, transform',
    '@media (max-width: 1200px)': {
      width: 260,
    },
    '@media (max-width: 768px)': {
      width: '100%',
      maxWidth: 320,
      left: 8,
      top: 8,
      bottom: 8,
      transform: 'translateX(0)',
    },
    '&.collapsed': {
      width: 72,
      '@media (max-width: 768px)': {
        transform: 'translateX(-100%)',
        width: 0,
      },
    },
  },
  sidebarWrapper: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: alpha(theme.palette.background.paper, 0.7),
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.1)}`,
    borderRadius: 20,
    boxShadow: `0 8px 32px ${alpha(theme.palette.common.black, 0.3)}, 0 0 0 1px ${alpha(theme.palette.common.white, 0.05)} inset`,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
  },
  toggleButton: {
    position: 'absolute' as const,
    right: -18,
    top: 20,
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: alpha(theme.palette.background.paper, 0.7),
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    border: `1px solid ${alpha(theme.palette.divider, 0.5)}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: `0 4px 16px ${alpha(theme.palette.common.black, 0.15)}`,
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 10,
    '&:hover': {
      backgroundColor: alpha(theme.palette.background.paper, 0.85),
      borderColor: alpha(theme.palette.primary.main, 0.4),
      transform: 'scale(1.08)',
      boxShadow: `0 6px 20px ${alpha(theme.palette.primary.main, 0.2)}`,
    },
    '&:active': {
      transform: 'scale(0.95)',
    },
    '& svg': {
      fontSize: 20,
      color: theme.palette.text.secondary,
      transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    },
    '&:hover svg': {
      color: theme.palette.primary.main,
    },
    '@media (max-width: 768px)': {
      right: -40,
      width: 40,
      height: 40,
      borderRadius: 14,
      '& svg': {
        fontSize: 22,
      },
    },
    '&.collapsed': {
      '@media (max-width: 768px)': {
        right: 'auto',
        left: 16,
        borderRadius: 14,
      },
    },
  },
  ambientAudioContainer: {
    position: 'absolute' as const,
    bottom: 24,
    right: 24,
    zIndex: 999,
    '@media (max-width: 768px)': {
      bottom: 16,
      right: 16,
    },
  },
  loadingOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: alpha(theme.palette.background.default, 0.9),
    backdropFilter: 'blur(24px)',
    WebkitBackdropFilter: 'blur(24px)',
  },
}));
