import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';

export const useAppStyles = makeStyles((theme: Theme) => ({
  appContainer: {
    display: 'flex',
    height: '100vh',
    width: '100vw',
    backgroundColor: theme?.palette?.background?.default || '#0f172a',
    position: 'relative' as const,
    overflow: 'hidden',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
    marginLeft: 0,
    transition: 'margin-left 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  canvas: {
    flex: 1,
    width: '100%',
    height: '100%',
    touchAction: 'none',
    visibility: 'visible',
  },
  sidebarContainer: {
    position: 'fixed' as const,
    left: 0,
    top: 0,
    bottom: 0,
    width: 340,
    zIndex: 1000,
    transition: 'width 0.4s cubic-bezier(0.4, 0, 0.2, 1), transform 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    willChange: 'width, transform',
    '@media (max-width: 1200px)': {
      width: 300,
    },
    '@media (max-width: 768px)': {
      width: '100%',
      maxWidth: 320,
      transform: 'translateX(0)',
    },
    '&.collapsed': {
      width: 72,
      '@media (max-width: 768px)': {
        transform: 'translateX(-100%)',
        width: 0,
      },
    },
  },
  sidebarWrapper: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    background: `linear-gradient(180deg, ${theme?.palette?.background?.paper || '#1e293b'} 0%, ${theme?.palette?.background?.default || '#0f172a'} 100%)`,
    borderRight: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.1)'}`,
    boxShadow: `4px 0 32px ${theme?.palette?.mode === 'dark' ? 'rgba(0, 0, 0, 0.5)' : 'rgba(0, 0, 0, 0.15)'}`,
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    overflow: 'hidden',
  },
  toggleButton: {
    position: 'absolute' as const,
    right: -16,
    top: 20,
    width: 36,
    height: 36,
    borderRadius: 8,
    background: `linear-gradient(135deg, ${theme?.palette?.background?.paper || '#1e293b'} 0%, ${theme?.palette?.background?.default || '#0f172a'} 100%)`,
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.12)'}`,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: `2px 2px 12px ${theme?.palette?.mode === 'dark' ? 'rgba(0, 0, 0, 0.3)' : 'rgba(0, 0, 0, 0.1)'}`,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    zIndex: 10,
    '&:hover': {
      background: `linear-gradient(135deg, ${theme?.palette?.primary?.main || '#4ade80'}15, ${theme?.palette?.background?.paper || '#1e293b'} 100%)`,
      borderColor: `${theme?.palette?.primary?.main || '#4ade80'}40`,
      right: -20,
      transform: 'scale(1.05)',
      boxShadow: `2px 4px 16px ${theme?.palette?.primary?.main || '#4ade80'}20`,
    },
    '& svg': {
      fontSize: 20,
      color: theme?.palette?.text?.secondary || '#94a3b8',
      transition: 'all 0.3s ease',
    },
    '&:hover svg': {
      color: theme?.palette?.primary?.main || '#4ade80',
    },
    '@media (max-width: 768px)': {
      right: -36,
      width: 40,
      height: 40,
      borderRadius: 10,
      '& svg': {
        fontSize: 22,
      },
    },
    '&.collapsed': {
      '@media (max-width: 768px)': {
        right: 'auto',
        left: 16,
        borderRadius: 10,
        border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.12)'}`,
      },
    },
  },
  ambientAudioContainer: {
    position: 'absolute' as const,
    bottom: 24,
    right: 24,
    zIndex: 999,
    '@media (max-width: 768px)': {
      bottom: 16,
      right: 16,
    },
  },
  loadingOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: `linear-gradient(135deg, ${theme?.palette?.background?.default || '#0f172a'} 0%, ${theme?.palette?.background?.paper || '#1e293b'} 100%)`,
    backdropFilter: 'blur(8px)',
  },
}));
