import { Theme, alpha } from '@mui/material/styles';
import { makeStyles } from '@mui/styles';

export const useLeftSidebarStyles = makeStyles((theme: Theme) => ({
  sidebar: {
    height: '100%',
    width: '100%',
    background: 'transparent',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
  },
  sidebarCollapsed: {},
  sidebarExpanded: {},

  // Header - PalmGuard
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '16px 16px',
    minHeight: 64,
    transition: 'all 0.3s ease',
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    opacity: 1,
    transform: 'translateX(0)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    whiteSpace: 'nowrap',
  },
  headerTitleCollapsed: {
    opacity: 0,
    transform: 'translateX(-16px)',
    pointerEvents: 'none',
  },
  headerIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 10,
    background: `linear-gradient(135deg, ${theme.palette.primary.main}, ${theme.palette.info.main})`,
    color: theme.palette.common.white,
    flexShrink: 0,
    '& svg': {
      fontSize: 20,
    },
  },
  titleText: {
    fontWeight: 700,
    color: theme.palette.text.primary,
    fontSize: '1.25rem',
    letterSpacing: '-0.01em',
    lineHeight: 1.2,
    textShadow: `0 0 20px ${alpha(theme.palette.common.white, 0.3)}`,
  },
  subtitleText: {
    fontSize: '0.8rem',
    color: theme.palette.text.secondary,
    fontWeight: 400,
    marginTop: 2,
    textShadow: `0 0 10px ${alpha(theme.palette.common.white, 0.2)}`,
  },

  // Collapsed state
  collapsedContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    padding: '16px 12px',
    opacity: 1,
    transform: 'scale(1)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'absolute',
    top: 72,
    left: 0,
    right: 0,
  },
  collapsedContentHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'scale(0.85)',
  },
  collapsedIconButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.12)}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    color: theme.palette.text.secondary,
    '&:hover': {
      backgroundColor: alpha(theme.palette.common.white, 0.12),
      color: theme.palette.primary.main,
    },
  },
  collapsedIcon: {
    fontSize: '20px !important',
  },

  // Tabs - Overview | Trees
  tabsContainer: {
    display: 'flex',
    padding: '0 16px 16px',
    gap: 0,
    opacity: 1,
    transform: 'translateY(0)',
    transition: 'all 0.3s ease-in-out',
  },
  tabsContainerHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(-8px)',
  },
  tabButton: {
    flex: 1,
    padding: '12px 24px',
    fontSize: '1rem',
    fontWeight: 500,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    backdropFilter: 'blur(15px)',
    WebkitBackdropFilter: 'blur(15px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.2)}`,
    borderRadius: 0,
    cursor: 'pointer',
    transition: 'all 0.3s ease-in-out',
    color: theme.palette.text.secondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textShadow: `0 0 10px ${alpha(theme.palette.common.white, 0.15)}`,
    '&:first-child': {
      borderRadius: '12px 0 0 12px',
      borderRight: 'none',
    },
    '&:last-child': {
      borderRadius: '0 12px 12px 0',
    },
    '&:hover': {
      color: theme.palette.text.primary,
      backgroundColor: alpha(theme.palette.common.white, 0.15),
      transform: 'translateY(-1px)',
      boxShadow: `0 4px 12px ${alpha(theme.palette.common.black, 0.1)}, 0 0 20px ${alpha(theme.palette.primary.main, 0.1)}`,
      textShadow: `0 0 15px ${alpha(theme.palette.common.white, 0.3)}`,
    },
  },
  tabButtonActive: {
    color: theme.palette.text.primary,
    background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.25)}, ${alpha(theme.palette.info.main, 0.2)})`,
    backgroundColor: alpha(theme.palette.common.white, 0.25),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    fontWeight: 600,
    boxShadow: `0 4px 16px ${alpha(theme.palette.primary.main, 0.2)}, 0 0 30px ${alpha(theme.palette.primary.main, 0.15)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.3)}`,
    textShadow: `0 0 20px ${alpha(theme.palette.common.white, 0.4)}`,
  },

  // Tab Content
  tabContent: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '0 16px 16px',
    opacity: 1,
    transform: 'translateX(0)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    '&::-webkit-scrollbar': {
      width: 4,
    },
    '&::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    '&::-webkit-scrollbar-thumb': {
      background: alpha(theme.palette.common.white, 0.15),
      borderRadius: 2,
    },
  },
  tabContentHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateX(-16px)',
  },

  // Stats Row - Combined Card
  statsRow: {
    display: 'flex',
    alignItems: 'stretch',
    gap: 0,
    marginBottom: 16,
    padding: '24px 20px',
    borderRadius: 20,
    backgroundColor: alpha(theme.palette.common.white, 0.12),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.25)}`,
    boxShadow: `0 8px 32px ${alpha(theme.palette.common.black, 0.15)}, 0 0 60px ${alpha(theme.palette.primary.main, 0.08)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.2)}`,
    transition: 'all 0.3s ease-in-out',
    position: 'relative' as const,
    '&:hover': {
      backgroundColor: alpha(theme.palette.common.white, 0.18),
      transform: 'translateY(-2px)',
      boxShadow: `0 12px 40px ${alpha(theme.palette.common.black, 0.18)}, 0 0 80px ${alpha(theme.palette.primary.main, 0.12)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.25)}`,
    },
    '&::after': {
      content: '""',
      position: 'absolute' as const,
      left: '50%',
      top: '20%',
      bottom: '20%',
      width: 1,
      background: `linear-gradient(to bottom, transparent, ${alpha(theme.palette.common.white, 0.4)}, transparent)`,
      boxShadow: `0 0 8px ${alpha(theme.palette.common.white, 0.3)}`,
    },
  },
  statCard: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  statHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  statIcon: {
    fontSize: '26px !important',
    color: theme.palette.text.secondary,
    opacity: 0.8,
    filter: `drop-shadow(0 0 8px ${alpha(theme.palette.common.white, 0.3)})`,
  },
  statIconHealthy: {
    fontSize: '20px !important',
    color: theme.palette.success.main,
    filter: `drop-shadow(0 0 8px ${alpha(theme.palette.success.main, 0.5)})`,
  },
  statIconTemp: {
    fontSize: '24px !important',
    color: theme.palette.error.light,
    filter: `drop-shadow(0 0 8px ${alpha(theme.palette.error.light, 0.5)})`,
  },
  statLabel: {
    fontSize: '1.1rem',
    color: theme.palette.text.secondary,
    fontWeight: 500,
    letterSpacing: '0.02em',
    textShadow: `0 0 12px ${alpha(theme.palette.common.white, 0.2)}`,
  },
  statValue: {
    fontSize: '3.5rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    lineHeight: 1,
    textShadow: `0 2px 12px ${alpha(theme.palette.common.black, 0.15)}, 0 0 30px ${alpha(theme.palette.common.white, 0.15)}`,
    marginTop: 8,
  },

  // Donut Section
  donutSection: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20px',
    marginBottom: 12,
    borderRadius: 20,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.2)}`,
    boxShadow: `0 4px 20px ${alpha(theme.palette.common.black, 0.1)}, 0 0 40px ${alpha(theme.palette.primary.main, 0.08)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.15)}`,
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      backgroundColor: alpha(theme.palette.common.white, 0.12),
      boxShadow: `0 6px 24px ${alpha(theme.palette.common.black, 0.12)}, 0 0 50px ${alpha(theme.palette.primary.main, 0.12)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.2)}`,
    },
  },
  donutWrapper: {
    position: 'relative',
    width: 140,
    height: 140,
  },
  donutCenter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutCenterValue: {
    fontSize: '2.5rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    lineHeight: 1,
    textShadow: `0 2px 12px ${alpha(theme.palette.common.black, 0.15)}, 0 0 40px ${alpha(theme.palette.common.white, 0.2)}`,
  },
  donutCenterLabel: {
    fontSize: '0.9rem',
    color: theme.palette.text.secondary,
    marginTop: 4,
    fontWeight: 500,
    textShadow: `0 0 15px ${alpha(theme.palette.common.white, 0.2)}`,
  },

  // Status Legend - Horizontal
  statusLegend: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    marginBottom: 20,
    padding: '12px 16px',
    borderRadius: 16,
    backgroundColor: alpha(theme.palette.common.white, 0.08),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.2)}`,
    boxShadow: `0 4px 16px ${alpha(theme.palette.common.black, 0.1)}, 0 0 30px ${alpha(theme.palette.primary.main, 0.06)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.15)}`,
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      backgroundColor: alpha(theme.palette.common.white, 0.12),
      boxShadow: `0 6px 20px ${alpha(theme.palette.common.black, 0.12)}, 0 0 40px ${alpha(theme.palette.primary.main, 0.1)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.2)}`,
    },
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: '50%',
    boxShadow: '0 0 10px currentColor, 0 0 16px currentColor, 0 0 24px currentColor',
  },
  legendDotHealthy: {
    backgroundColor: theme.palette.success.main,
  },
  legendDotWarning: {
    backgroundColor: theme.palette.warning.main,
  },
  legendDotCritical: {
    backgroundColor: theme.palette.error.main,
  },
  legendDotUnknown: {
    backgroundColor: theme.palette.info.main,
  },
  legendValue: {
    fontSize: '1rem',
    fontWeight: 600,
    color: theme.palette.text.primary,
    textShadow: `0 0 15px ${alpha(theme.palette.common.white, 0.2)}`,
  },

  // Robot Fleet Section
  robotFleetSection: {
    marginTop: 8,
  },
  robotFleetTitle: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: theme.palette.text.secondary,
    letterSpacing: '0.1em',
    marginBottom: 12,
    textTransform: 'uppercase' as const,
    textShadow: `0 0 12px ${alpha(theme.palette.common.white, 0.2)}`,
  },
  robotList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  robotItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 16px',
    borderRadius: 16,
    backgroundColor: alpha(theme.palette.common.white, 0.1),
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    border: `1px solid ${alpha(theme.palette.common.white, 0.2)}`,
    boxShadow: `0 4px 16px ${alpha(theme.palette.common.black, 0.1)}, 0 0 30px ${alpha(theme.palette.info.main, 0.05)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.15)}`,
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      backgroundColor: alpha(theme.palette.common.white, 0.15),
      transform: 'translateY(-2px)',
      boxShadow: `0 8px 24px ${alpha(theme.palette.common.black, 0.12)}, 0 0 40px ${alpha(theme.palette.info.main, 0.1)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.2)}`,
    },
  },
  robotInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  robotIcon: {
    fontSize: '22px !important',
    color: theme.palette.info.main,
    filter: `drop-shadow(0 0 10px ${alpha(theme.palette.info.main, 0.5)})`,
  },
  robotName: {
    fontSize: '1rem',
    fontWeight: 600,
    color: theme.palette.text.primary,
    textShadow: `0 0 15px ${alpha(theme.palette.common.white, 0.2)}`,
  },
  robotStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  robotStatusText: {
    fontSize: '0.85rem',
    color: theme.palette.text.secondary,
    textShadow: `0 0 10px ${alpha(theme.palette.common.white, 0.15)}`,
  },
  robotStatusBar: {
    width: 32,
    height: 7,
    borderRadius: 4,
    transition: 'all 0.3s ease-in-out',
  },
  robotStatusIdle: {
    background: `linear-gradient(90deg, ${theme.palette.success.main}, ${theme.palette.success.light})`,
    boxShadow: `0 0 16px ${theme.palette.success.main}, 0 0 28px ${alpha(theme.palette.success.main, 0.5)}, 0 0 40px ${alpha(theme.palette.success.main, 0.3)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.4)}`,
  },
  robotStatusWorking: {
    background: `linear-gradient(90deg, ${theme.palette.warning.main}, ${theme.palette.warning.light})`,
    boxShadow: `0 0 16px ${theme.palette.warning.main}, 0 0 28px ${alpha(theme.palette.warning.main, 0.5)}, 0 0 40px ${alpha(theme.palette.warning.main, 0.3)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.4)}`,
  },
  robotStatusCharging: {
    background: `linear-gradient(90deg, ${theme.palette.info.main}, ${theme.palette.info.light})`,
    boxShadow: `0 0 16px ${theme.palette.info.main}, 0 0 28px ${alpha(theme.palette.info.main, 0.5)}, 0 0 40px ${alpha(theme.palette.info.main, 0.3)}, inset 0 1px 0 ${alpha(theme.palette.common.white, 0.4)}`,
  },

  // Trees Section
  treesSection: {
    paddingTop: 8,
  },
  treesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },

  // Empty State
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    color: theme.palette.text.secondary,
    textAlign: 'center',
    backgroundColor: alpha(theme.palette.common.white, 0.05),
    borderRadius: 16,
    border: `1px solid ${alpha(theme.palette.common.white, 0.08)}`,
    '& .MuiTypography-root': {
      fontSize: '0.85rem',
    },
  },
  emptyStateIcon: {
    fontSize: '40px !important',
    marginBottom: 12,
    opacity: 0.4,
  },
}));
