import { makeStyles } from '@mui/styles';
import { Theme } from '@mui/material/styles';

export const useLeftSidebarStyles = makeStyles((theme: Theme) => ({
  sidebar: {
    height: '100%',
    width: '100%',
    background: 'transparent',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
  },
  sidebarCollapsed: {},
  sidebarExpanded: {},
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: '16px 20px',
    borderBottom: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.08)'}`,
    minHeight: 72,
    background: `linear-gradient(90deg, ${theme?.palette?.primary?.main || '#4ade80'}06, transparent)`,
    transition: 'all 0.3s ease',
    '@media (max-width: 768px)': {
      padding: '12px 16px',
      minHeight: 64,
    },
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    opacity: 1,
    transform: 'translateX(0)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    whiteSpace: 'nowrap',
  },
  headerTitleCollapsed: {
    opacity: 0,
    transform: 'translateX(-16px)',
    pointerEvents: 'none',
  },
  headerIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 10,
    background: `linear-gradient(135deg, ${theme?.palette?.primary?.main || '#4ade80'}18, ${theme?.palette?.primary?.main || '#4ade80'}05)`,
    border: `1px solid ${theme?.palette?.primary?.main || '#4ade80'}25`,
    color: theme?.palette?.primary?.main || '#4ade80',
    flexShrink: 0,
    '& svg, & .MuiIcon-root': {
      fontSize: 22,
    },
  },
  titleText: {
    fontWeight: 700,
    color: theme?.palette?.text?.primary || '#f1f5f9',
    fontSize: '1.1rem',
    letterSpacing: '-0.02em',
  },
  collapsedContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    padding: '16px 12px',
    opacity: 1,
    transform: 'scale(1)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'absolute',
    top: 88,
    left: 0,
    right: 0,
  },
  collapsedContentHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'scale(0.85)',
  },
  collapsedIconButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    background: `linear-gradient(135deg, ${theme?.palette?.action?.disabledBackground || 'rgba(148, 163, 184, 0.08)'} 0%, transparent 100%)`,
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.1)'}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    color: theme?.palette?.text?.secondary || '#94a3b8',
    '&:hover': {
      background: `linear-gradient(135deg, ${theme?.palette?.primary?.main || '#4ade80'}12, ${theme?.palette?.primary?.main || '#4ade80'}04)`,
      borderColor: `${theme?.palette?.primary?.main || '#4ade80'}35`,
      color: theme?.palette?.primary?.main || '#4ade80',
      transform: 'scale(1.08)',
      boxShadow: `0 6px 20px ${theme?.palette?.primary?.main || '#4ade80'}18`,
    },
  },
  collapsedIcon: {
    fontSize: '22px !important',
  },
  tabsContainer: {
    display: 'flex',
    padding: '8px 12px',
    gap: 8,
    borderBottom: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.08)'}`,
    opacity: 1,
    transform: 'translateY(0)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    background: `${theme?.palette?.background?.paper || '#1e293b'}30`,
    '@media (max-width: 768px)': {
      padding: '6px 10px',
    },
  },
  tabsContainerHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateY(-8px)',
  },
  tabButton: {
    flex: 1,
    padding: '10px 14px',
    fontSize: '0.8rem',
    fontWeight: 600,
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    transition: 'all 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
    color: theme?.palette?.text?.secondary || '#94a3b8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    '& svg, & .MuiIcon-root': {
      fontSize: 18,
    },
    '&:hover': {
      color: theme?.palette?.text?.primary || '#f1f5f9',
      background: `${theme?.palette?.action?.hover || 'rgba(74, 222, 128, 0.06)'}`,
    },
    '@media (max-width: 768px)': {
      padding: '8px 10px',
      fontSize: '0.75rem',
    },
  },
  tabButtonActive: {
    color: theme?.palette?.primary?.main || '#4ade80',
    background: `linear-gradient(135deg, ${theme?.palette?.primary?.main || '#4ade80'}12, ${theme?.palette?.primary?.main || '#4ade80'}04)`,
    boxShadow: `0 2px 8px ${theme?.palette?.primary?.main || '#4ade80'}12`,
  },
  tabContent: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: 16,
    opacity: 1,
    transform: 'translateX(0)',
    transition: 'all 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
    '&::-webkit-scrollbar': {
      width: 4,
    },
    '&::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    '&::-webkit-scrollbar-thumb': {
      background: theme?.palette?.divider || 'rgba(148, 163, 184, 0.15)',
      borderRadius: 2,
    },
    '@media (max-width: 768px)': {
      padding: 12,
    },
  },
  tabContentHidden: {
    opacity: 0,
    pointerEvents: 'none',
    transform: 'translateX(-16px)',
  },
  section: {
    marginBottom: 24,
    '@media (max-width: 768px)': {
      marginBottom: 20,
    },
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  sectionIcon: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 7,
    background: `${theme?.palette?.primary?.main || '#4ade80'}10`,
    color: theme?.palette?.primary?.main || '#4ade80',
    '& svg, & .MuiIcon-root': {
      fontSize: 16,
    },
  },
  sectionTitle: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: theme?.palette?.text?.secondary || '#94a3b8',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 12,
    '@media (max-width: 400px)': {
      gridTemplateColumns: '1fr',
      gap: 10,
    },
  },
  healthCard: {
    border: `1px solid ${theme?.palette?.divider || 'rgba(148, 163, 184, 0.08)'}`,
    borderRadius: 14,
    padding: 16,
    background: `linear-gradient(135deg, ${theme?.palette?.background?.paper || '#1e293b'}80 0%, ${theme?.palette?.background?.default || '#0f172a'}60 100%)`,
    boxShadow: `0 4px 12px ${theme?.palette?.mode === 'dark' ? 'rgba(0, 0, 0, 0.25)' : 'rgba(0, 0, 0, 0.08)'}`,
    '@media (max-width: 768px)': {
      padding: 14,
      borderRadius: 12,
    },
  },
  donutContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  donutWrapper: {
    position: 'relative',
    width: 100,
    height: 100,
    '@media (max-width: 768px)': {
      width: 90,
      height: 90,
    },
  },
  donutCenter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutCenterText: {
    fontSize: '1.5rem',
    fontWeight: 800,
    color: theme?.palette?.text?.primary || '#f1f5f9',
    lineHeight: 1,
    '@media (max-width: 768px)': {
      fontSize: '1.25rem',
    },
  },
  donutCenterLabel: {
    fontSize: '0.65rem',
    color: theme?.palette?.text?.secondary || '#94a3b8',
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  statusGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 10,
    textAlign: 'center',
  },
  statusItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 10,
    borderRadius: 10,
    background: `${theme?.palette?.action?.disabledBackground || 'rgba(148, 163, 184, 0.04)'}`,
    transition: 'all 0.2s ease',
    '&:hover': {
      transform: 'translateY(-1px)',
      background: `${theme?.palette?.action?.hover || 'rgba(148, 163, 184, 0.06)'}`,
    },
  },
  statusLabel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    marginBottom: 4,
  },
  statusLabelText: {
    fontSize: '0.65rem',
    color: theme?.palette?.text?.secondary || '#94a3b8',
    fontWeight: 500,
  },
  statusValue: {
    fontSize: '1rem',
    fontFamily: 'monospace',
    fontWeight: 700,
  },
  statusValueHealthy: {
    color: theme?.palette?.success?.main || '#10b981',
  },
  statusValueWarning: {
    color: theme?.palette?.warning?.main || '#f59e0b',
  },
  statusValueCritical: {
    color: theme?.palette?.error?.main || '#ef4444',
  },
  alertsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  treesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    boxShadow: '0 0 6px currentColor',
  },
  statusDotHealthy: {
    backgroundColor: theme?.palette?.success?.main || '#10b981',
  },
  statusDotWarning: {
    backgroundColor: theme?.palette?.warning?.main || '#f59e0b',
  },
  statusDotCritical: {
    backgroundColor: theme?.palette?.error?.main || '#ef4444',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    color: theme?.palette?.text?.secondary || '#94a3b8',
    textAlign: 'center',
    '& .MuiTypography-root': {
      fontSize: '0.85rem',
    },
  },
  emptyStateIcon: {
    fontSize: '40px !important',
    marginBottom: 12,
    opacity: 0.4,
  },
}));
